### PR TITLE
Add IYLoginItem git url to Podfile

### PR DESCRIPTION
**Pull request by linclark**
I'm not sure whether this is actually necessary because this is the first time I'm building anything with pod, so I might just be doing it wrong, but I kept getting the error `[!] Unable to find a specification for `IYLoginItem``when I tried to`pod install`. Adding this fixed the error.

### CODE REVIEW

**Comment by tadeuzagallo** [comment]
Hum, that's weird, because the specification is there... https://github.com/CocoaPods/Specs/blob/master/Specs/IYLoginItem/0.1/IYLoginItem.podspec.json

If you run a `pod search IYLoginItem` you can't find it as well?

**Comment by linclark** [comment]
Maybe that's it... when I ran that command, the first line of output was `Setting up CocoaPods master repo`. I'm guessing you need to set that up before you can run a `pod install`.

**Comment by tadeuzagallo** [comment]
I guess you have to run `pod setup` before installing the dependencies...
Did you manage to install it?

**Comment by linclark** [comment]
Yep, `pod install` runs just fine now :) I'll file a PR with a note in the README

**Pull request closed without merging**
